version: '3.8'

services:
  product_postgres:
    image: postgres
    container_name: discount_postgres
    read_only: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=discountDb
    expose:
      - "5432"
    ports:
      - "5432:5432"
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - discount-volume:/var/lib/postgresql/data
    command: -p 5432

volumes:
  discount-volume: